# Generated by Django 3.0.1 on 2020-01-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuidadoMascota',
            fields=[
                ('idcuidado_mascota', models.IntegerField(db_column='idCuidado_Mascota', primary_key=True, serialize=False)),
                ('fechacuidado', models.DateTimeField(blank=True, db_column='fechaCuidado', null=True)),
                ('detallecuidado', models.CharField(blank=True, db_column='detalleCuidado', max_length=100, null=True)),
                ('likecuidado', models.IntegerField(blank=True, db_column='likeCuidado', null=True)),
            ],
            options={
                'db_table': 'cuidado_mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idlocal', models.IntegerField(db_column='idLocal', primary_key=True, serialize=False)),
                ('localdireccion', models.CharField(blank=True, db_column='localDireccion', max_length=45, null=True)),
                ('localtelefono', models.CharField(blank=True, db_column='localTelefono', max_length=45, null=True)),
                ('localmail', models.CharField(blank=True, db_column='localMail', max_length=45, null=True)),
            ],
            options={
                'db_table': 'local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idmascota', models.IntegerField(db_column='idMascota', primary_key=True, serialize=False)),
                ('nombremascota', models.CharField(blank=True, db_column='nombreMascota', max_length=45, null=True)),
                ('edadmascota', models.IntegerField(blank=True, db_column='edadMascota', null=True)),
                ('sexomascota', models.CharField(blank=True, db_column='sexoMascota', max_length=10, null=True)),
                ('alimentacionmascota', models.CharField(blank=True, db_column='alimentacionMascota', max_length=100, null=True)),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.IntegerField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombrepersona', models.CharField(blank=True, db_column='nombrePersona', max_length=45, null=True)),
                ('apellidopersona', models.CharField(blank=True, db_column='apellidoPersona', max_length=45, null=True)),
                ('direccionpersona', models.CharField(blank=True, db_column='direccionPersona', max_length=45, null=True)),
                ('mailpersona', models.CharField(blank=True, db_column='mailPersona', max_length=45, null=True)),
                ('generopersona', models.CharField(blank=True, db_column='generoPersona', max_length=45, null=True)),
                ('edadpersona', models.IntegerField(blank=True, db_column='edadPersona', null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planificacionvacuna',
            fields=[
                ('idplanificacionvacuna', models.IntegerField(db_column='idPlanificacionVacuna', primary_key=True, serialize=False)),
                ('fechavacuna', models.DateTimeField(db_column='fechaVacuna')),
                ('dosisvacuna', models.DecimalField(blank=True, db_column='dosisVacuna', decimal_places=2, max_digits=5, null=True)),
                ('descripcionplanificacion', models.CharField(blank=True, db_column='descripcionPlanificacion', max_length=100, null=True)),
                ('aplicadavacuna', models.IntegerField(blank=True, db_column='aplicadaVacuna', null=True)),
            ],
            options={
                'db_table': 'planificacionvacuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('idpropietario', models.IntegerField(db_column='idPropietario', primary_key=True, serialize=False)),
                ('numeromascotas', models.IntegerField(db_column='numeroMascotas')),
            ],
            options={
                'db_table': 'propietario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idraza', models.IntegerField(db_column='idRaza', primary_key=True, serialize=False)),
                ('razanombre', models.CharField(blank=True, db_column='razaNombre', max_length=45, null=True)),
                ('razadescripcion', models.CharField(blank=True, db_column='razaDescripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'raza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recomendarlugar',
            fields=[
                ('idrecomendarlugar', models.IntegerField(db_column='idRecomendarLugar', primary_key=True, serialize=False)),
                ('recomendacionfecha', models.DateTimeField(blank=True, db_column='recomendacionFecha', null=True)),
                ('recomnedacionlike', models.IntegerField(blank=True, db_column='recomnedacionLike', null=True)),
                ('recomendaciondescripcion', models.CharField(blank=True, db_column='recomendacionDescripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'recomendarlugar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('idtipo', models.IntegerField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(blank=True, db_column='nombreTipo', max_length=45, null=True)),
                ('descripciontipo', models.CharField(blank=True, db_column='descripcionTipo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=45, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=65, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('idvacuna', models.IntegerField(db_column='idVacuna', primary_key=True, serialize=False)),
                ('nombrevacuna', models.CharField(blank=True, db_column='nombreVacuna', max_length=45, null=True)),
                ('fabricantevacuna', models.CharField(blank=True, db_column='fabricanteVacuna', max_length=45, null=True)),
                ('descripcionvacuna', models.CharField(blank=True, db_column='descripcionVacuna', max_length=100, null=True)),
            ],
            options={
                'db_table': 'vacuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('idveterinario', models.IntegerField(db_column='idVeterinario', primary_key=True, serialize=False)),
                ('veterinariotitulo', models.CharField(blank=True, db_column='veterinarioTitulo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'veterinario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitaVeterinario',
            fields=[
                ('idvisita_veterinario', models.IntegerField(db_column='idVisita_Veterinario', primary_key=True, serialize=False)),
                ('fechavisita', models.DateTimeField(db_column='fechaVisita')),
                ('descripcionvisita', models.CharField(blank=True, db_column='descripcionVisita', max_length=100, null=True)),
            ],
            options={
                'db_table': 'visita_veterinario',
                'managed': False,
            },
        ),
    ]
