# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidado',
            fields=[
                ('idcuidado', models.AutoField(primary_key=True, serialize=False)),
                ('cuidadofecha', models.DateField(default=None)),
                ('cuidadodetalle', models.CharField(max_length=300)),
                ('cuidadolike', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idlocal', models.AutoField(primary_key=True, serialize=False)),
                ('localnombre', models.CharField(max_length=20)),
                ('localdireccion', models.CharField(max_length=50)),
                ('localtelefono', models.CharField(max_length=10)),
                ('localmail', models.CharField(max_length=20)),
                ('localPropietario', models.CharField(max_length=50)),
                ('locallike', models.IntegerField(default=None)),
                ('localfoto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idmascota', models.AutoField(primary_key=True, serialize=False)),
                ('mascotanombre', models.CharField(max_length=100)),
                ('mascotaedad', models.IntegerField(default=None)),
                ('mascotasexo', models.CharField(max_length=10)),
                ('mascotafoto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('idplanificacion', models.AutoField(primary_key=True, serialize=False)),
                ('planificacionfecha', models.DateField(default=None)),
                ('planificaciondescripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idraza', models.AutoField(primary_key=True, serialize=False)),
                ('razanombre', models.CharField(max_length=30)),
                ('razadescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendar',
            fields=[
                ('idrecomendar', models.AutoField(primary_key=True, serialize=False)),
                ('recomendarfecha', models.DateField(default=None)),
                ('recomendardetalle', models.CharField(max_length=200)),
                ('idlocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('roltipo', models.CharField(max_length=10)),
                ('roldescripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('tiponombre', models.CharField(max_length=30)),
                ('tipodescripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuariopassword', models.CharField(max_length=65)),
                ('usuarionombre', models.CharField(max_length=20)),
                ('usuarioapellido', models.CharField(max_length=20)),
                ('usuariomail', models.CharField(max_length=20)),
                ('usuariodireccion', models.CharField(max_length=80)),
                ('usuarionickname', models.CharField(max_length=20)),
                ('usuariofoto', models.CharField(max_length=300)),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='recomendar',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Usuario'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Usuario'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='idraza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Raza'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='idtipomascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.TipoMascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Usuario'),
        ),
        migrations.AddField(
            model_name='cuidado',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Usuario'),
        ),
    ]
